use_frameworks!
platform :ios, '10.0'

target 'Component_Tests' do
  pod 'Base', :path => '../../Base'
  pod 'Component', :path => '../'
  pod 'Component/Drawer', :path => '../'
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
end
